# Interior Design Prompts Library v3 (Production Ready - Final)
from .interior_design_prompts_v3 import (
    # 核心类
    PromptBuilder,
    PromptResult,
    TaskMode,
    Engine,
    QualityLevel,
    MaskContract,
    BlendSpec,
    # 预设数据
    STYLE_PRESETS,
    ROOM_TYPES,
    MATERIAL_PRESETS,
    QUALITY_PRESETS,
    QUALITY_EDGE_BLEND,
    MASK_CONTRACTS,
    ENGINE_PARAMS,
    ENGINE_PARAMS_DEFAULT,
    ENGINE_PARAMS_RANGE,
    ENUM_DEFAULTS,
    # Mask 词表
    MASK_CLASS_VOCAB,
    MASK_VOCAB_VERSION,
    AMBIGUOUS_CLASSES,
    VALID_REPLACE_SCOPES,
    EDGE_BLEND_PROTECT_BY_SURFACE,
    normalize_replace_scope,
    create_scoped_contract,
    # 结构锁定
    STRUCT_LOCK_HARD,
    STRUCT_LOCK_MJ,
    STRUCT_HINT_CONTROLNET,
    # 保护指令
    PRESERVE_MATERIAL_REPLACE,
    PRESERVE_FURNITURE_ADD,
    CONSISTENCY_EDGE_BLEND,
    OBJECT_INTEGRITY_LOCK,
    # 负面提示词
    NEGATIVE_BY_ENGINE,
    NEGATIVE_BY_TASK,
    NEGATIVE_QUALITY,
    NEGATIVE_STRUCTURE,
    NEGATIVE_CGI,
    NEGATIVE_SEAMS,
    # 便捷函数
    generate_prompt,
    get_negative_prompt,
    get_edge_blend_prompt,
    get_mask_contract,
    resolve_mask_class,
    validate_mask_contract,
    # Negative 分离
    NEGATIVE_QUALITY_BASE,
    NEGATIVE_NOISE,
    # Legacy exports（DEPRECATED）
    STYLE_PROMPTS,
    ROOM_PROMPTS,
    STYLE_TEMPLATES,
    ROOM_TEMPLATES,
    MASTER_PROMPT_EN,
    MASTER_PROMPT_ZH,
    NEGATIVE_PROMPT,
    QUALITY_POSITIVE,
    QUALITY_NEGATIVE,
    QUALITY_KEYWORDS,
    NEGATIVE_PROMPTS,
    DEFAULT_NEGATIVE,
    FULL_NEGATIVE,
)

# Professional Vocabulary Dictionary
from .professional_vocabulary import (
    MATERIALS,
    LIGHTING,
    PHOTOGRAPHY,
    COLORS,
    FURNITURE,
    DECORATIVE,
    QUALITY,
    NEGATIVE_PROMPTS as PRO_NEGATIVE_PROMPTS,
    DESIGNERS,
    get_material_prompt,
    get_lighting_prompt,
    get_color_palette,
    get_quality_prompt,
    get_negative_prompt as get_pro_negative_prompt,
    build_professional_prompt,
)
